[project]
name = "calmzeus"
version = "0.0.1"
description = "Exploration for project 'peacefulares'"
authors = [{ name = "lo-b", email = "bram_lo@outlook.com" }]
requires-python = "~=3.9"
readme = "README.md"
dependencies = [
    "notebook>=6.5.1,<7.0.0",
    "faiss-cpu>=1.8.0.post1,<2",
    "langchain>=0.3.2,<0.4",
    "voyageai>=0.2.3,<0.3",
    "load-dotenv>=0.1.0,<0.2",
    "langchain-community>=0.3.1,<0.4",
    "tree-sitter==0.21.3",
    "tree-sitter-languages>=1.10.2,<2",
    "langchain-voyageai>=0.1.2,<0.2",
    "rich>=13.9.2,<14",
    "langgraph>=0.2.35,<0.3",
    "langsmith>=0.1.133,<0.2",
    "langchain-ollama>=0.2.0,<0.3",
    "langchain-qdrant>=0.1.4,<0.2",
    "langchain-mistralai>=0.2.0,<0.3",
    "tree-sitter-python>=0.23.2,<0.24",
    "langchain-openai>=0.2.3,<0.3",
]

[dependency-groups]
dev = ["jupyter-ascending>=0.1.27,<0.2"]

[tool.basedpyright]
include = ["**/*.py"]
typeCheckingMode = "off"    # type checking done by mypy
reportUnusedImport = "none" # ruff already lints for this rule

[tool.ruff.lint]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
    # flake8-quotes
    "Q",
]
