[tool.poetry]
name = "calmzeus"
version = "0.0.1"
description = "Exploration for project 'peacefulares'"
authors = ["lo-b <bram_lo@outlook.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
